services:
  db:
    image: mysql:8.0
    container_name: life_tracker_mysql
    restart: always
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: life_tracker
    volumes:
      # 挂载数据库数据
      - mysql_data:/var/lib/mysql
      # 挂载初始化脚本
      - ./packages/db/mysql/docker-init:/docker-entrypoint-initdb.d
      # 挂载 schema 和 seeds 目录
      - ./packages/db/mysql/schema:/docker-entrypoint-initdb.d/schema
      - ./packages/db/mysql/seeds:/docker-entrypoint-initdb.d/seeds
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-ppassword123'
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--require_secure_transport=OFF',
        '--ssl=0',
        '--skip_ssl'
      ]

  web:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
      target: runner
      args:
        - DATABASE_URL=mysql://root:${DB_ROOT_PASSWORD}@db:3306/life_tracker?connect_timeout=300
    expose:
      - '3000'
    environment:
      - DEBUG=prisma:client,prisma:engine
      - DATABASE_URL=mysql://root:${DB_ROOT_PASSWORD}@db:3306/life_tracker?connect_timeout=300&charset=utf8mb4
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    container_name: life_tracker_nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d/${NGINX_CONF:-prod}.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - web
    restart: always

volumes:
  mysql_data:
