CREATE DATABASE IF NOT EXISTS life_tracker CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE life_tracker;

CREATE TABLE IF NOT EXISTS USER (
  user_id INT(8) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  display_name VARCHAR(100),
  avatar_url VARCHAR(255),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) AUTO_INCREMENT=100000 COMMENT='global USER 表';

CREATE TABLE IF NOT EXISTS GOAL_STATE (
  state_id INT(8) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) AUTO_INCREMENT=100000 COMMENT='global GOAL STATE 引用表';

CREATE TABLE IF NOT EXISTS UC_GOAL (
  goal_id INT(8) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT(8) UNSIGNED NOT NULL COMMENT '所属用户ID',
  color VARCHAR(7) NOT NULL,
  summary VARCHAR(100) NOT NULL,
  description TEXT,
  state_id INT(8) UNSIGNED NOT NULL COMMENT '状态ID',
  parent_id INT(8) UNSIGNED NULL COMMENT '父目标ID',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  
  CONSTRAINT fk_uc_goal_user FOREIGN KEY (user_id) REFERENCES USER(user_id) ON DELETE CASCADE,
  CONSTRAINT fk_uc_goal_state FOREIGN KEY (state_id) REFERENCES GOAL_STATE(state_id) ON DELETE RESTRICT,
  CONSTRAINT fk_uc_goal_parent FOREIGN KEY (parent_id) REFERENCES UC_GOAL(goal_id) ON DELETE SET NULL
) AUTO_INCREMENT=100000 COMMENT='用户GOAL表，支持树形结构';

CREATE TABLE IF NOT EXISTS UC_PROJECT_STATE (
  state_id INT(8) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT(8) UNSIGNED NOT NULL COMMENT '所属用户ID',
  name VARCHAR(50) NOT NULL COMMENT '状态名称',
  is_default BOOLEAN NOT NULL DEFAULT FALSE COMMENT '是否为默认状态',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  
  CONSTRAINT fk_uc_project_state_user FOREIGN KEY (user_id) REFERENCES USER(user_id) ON DELETE CASCADE,
  CONSTRAINT uk_uc_project_state_name UNIQUE (user_id, name)
) AUTO_INCREMENT=100000 COMMENT='用户项目状态表';

CREATE TABLE IF NOT EXISTS UC_PROJECT (
  project_id INT(8) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT(8) UNSIGNED NOT NULL COMMENT '所属用户ID',
  color VARCHAR(7) NOT NULL COMMENT '颜色代码',
  summary VARCHAR(100) NOT NULL COMMENT '项目名称',
  description TEXT COMMENT '项目描述',
  start_date DATETIME(3) NOT NULL COMMENT '开始日期',
  due_date DATETIME(3) NOT NULL COMMENT '截止日期',
  original_estimate_minutes INT NOT NULL COMMENT '预估时间（分钟）',
  time_spent_minutes INT NOT NULL DEFAULT 0 COMMENT '实际花费时间（分钟）',
  state_id INT(8) UNSIGNED NOT NULL COMMENT '状态ID',
  goal_id INT(8) UNSIGNED COMMENT '关联的目标ID',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  
  CONSTRAINT fk_uc_project_user FOREIGN KEY (user_id) REFERENCES USER(user_id) ON DELETE CASCADE,
  CONSTRAINT fk_uc_project_state FOREIGN KEY (state_id) REFERENCES UC_PROJECT_STATE(state_id) ON DELETE RESTRICT,
  CONSTRAINT fk_uc_project_goal FOREIGN KEY (goal_id) REFERENCES UC_GOAL(goal_id) ON DELETE SET NULL
) AUTO_INCREMENT=100000 COMMENT='用户项目表';

-- 项目状态模板表
CREATE TABLE IF NOT EXISTS PROJECT_STATE_TEMPLATE (
  template_id INT(8) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL COMMENT '状态名称',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) AUTO_INCREMENT=100000 COMMENT='项目状态模板表，用于初始化用户的默认项目状态';
